stages:
    - build
    - test
    - security_check

variables:
    POETRY_VERSION: 1.8.3

install_dependencies:
    stage: build
    image: python:3.12.7-alpine
    tags:
        - docker
    variables:
        POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/.venv
    before_script:
        - apk add curl
        - apk add git
        - curl -sSL https://install.python-poetry.org | POETRY_HOME=$CI_PROJECT_DIR/poetry python3 -
        - export PATH="/builds/justme5254252/fastapi-cicde/poetry/bin:$PATH"
        - poetry config virtualenvs.in-project true
    script:
        - poetry install
        - echo "$(date) Done----------------------------------------"
    artifacts:
        paths:
            - $CI_PROJECT_DIR/.venv
            - $CI_PROJECT_DIR/poetry
#    cache:
#        key:
#            files:
#                - poetry.lock
#        paths:
#            - /

run_pytest:
    stage: test
    image: python:3.12.7-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add curl
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry run pytest tests/*

run_mypy:
    stage: test
    image: python:3.12.7-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add curl
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry run mypy .

bandit_check:
    stage: security_check
    image: python:3.12.7-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add curl
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry add bandit
        - bandit -rv .


safety_check:
    stage: security_check
    image: python:3.12.7-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add curl
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry add safety
        - poetry export -f requirements.txt --output requirements.txt
        - safety check -r requirements.txt
