stages:
    - test1
    - test2
    - build
    - prod

test1:
    stage: test1
    script:
        - echo "$(date) test1 --------------------"
    only:
        refs:
            - develop1
    tags:
        - pi-5

pytest:
    stage: test2
    image: python:3.12-slim
    before_script:
        - pip install poetry==1.8.3
        - poetry install
    script:
        - poetry run pytest test.py
    only:
        refs:
            - develop1
    tags:
        - pi-5

build:
    stage: build
    script: echo "$(date) Building..."
    only:
        refs:
            - develop1
    when: manual

deploy_prod:
    stage: prod
    script: echo "$(date) Deploying to prod"
    when: manual
    only:
        refs:
            - tags
            - develop