image: python:3.12.7-slim
stages:
    - build
    - test
    - stage

variables:
    POETRY_VERSION: 1.8.3

install_dependencies:
    stage: build
    script:
        - pip install poetry==$POETRY_VERSION
        - poetry install
        - source `poetry env info --path`/bin/activate
        - echo "$PWD"
        - ls -la
    artifacts:
        paths:
            - .venv
    cache:
        key:
            files:
                - poetry.lock
        paths:
            - .venv

run_pytest:
    stage: test
    script:
        - poetry run pytest tests/*

run_mypy:
    stage: test
    script:
        - poetry run mypy .