stages:
    - build
    - test
    - security_check

variables:
    PYTHON_VERSION: 3.12.7

install_dependencies:
    stage: build
    image: python:$PYTHON_VERSION-alpine
    variables:
        POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/.venv
    before_script:
        - apk add curl
        - apk add git
        - curl -sSL https://install.python-poetry.org | POETRY_HOME=$CI_PROJECT_DIR/poetry python3 -
        - export PATH="/builds/justme5254252/fastapi-cicde/poetry/bin:$PATH"
        - poetry config virtualenvs.in-project true
    script:
        - poetry install
        - echo "$(date) Done----------------------------------------"
    artifacts:
        paths:
            - $CI_PROJECT_DIR/.venv
            - $CI_PROJECT_DIR/poetry
    cache:
        key:
            files:
                - poetry.lock
        paths:
            - $CI_PROJECT_DIR

run_pytest:
    stage: test
    image: python:$PYTHON_VERSION-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry run pytest tests/*

run_mypy:
    stage: test
    image: python:$PYTHON_VERSION-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry run mypy .

bandit_check:
    stage: security_check
    image: python:$PYTHON_VERSION-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add bash
        - apk add git
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry add bandit
        - ls -la
        - find . -type f -name "*.py" ! -path "./.venv/*"
        - find . -type f -name "*.py" ! -path "./.venv/*" | xargs bandit -r --exclude venv --format txt --output bandit_report.log || true
    artifacts:
        paths:
            - $CI_PROJECT_DIR/bandit_report.log


safety_check:
    stage: security_check
    image: python:$PYTHON_VERSION-alpine
    dependencies:
        - install_dependencies
    before_script:
        - apk add bash
        - apk add git
        - apk add gcc python3-dev musl-dev linux-headers
    script:
        - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
        - source $CI_PROJECT_DIR/.venv/bin/activate
        - poetry add safety
        - poetry export -f requirements.txt --output requirements.txt
        - safety check -r requirements.txt --json > safety_report.json || true
    artifacts:
        paths:
            - safety_report.json
