image: python3.12-slim
stages:
    - build
    - test
    - stage

variables:
    POETRY_VERSION: 1.8.3

install_dependencies:
    stage: build
    script:
        - pip install poetry==$POETRY_VERSION
        - poetry install
    artifacts:
        paths:
            - .venv
    cache:
        key:
            files:
                - poetry.lock
        paths:
            - .venv

run_pytest:
    stage: test
    script:
        - pytest tests/*

run_mypy:
    stage: test
    script:
        - mypy .